<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SarthakThinkpad" failures="1" tests="5" name="rerun_failed_testCases.Code" time="49.595" errors="0" timestamp="2023-04-14T14:01:37 GMT-04:00" skipped="3">
  <testcase classname="rerun_failed_testCases.Code" name="clickOnSigninLink" time="7.213"/>
  <system-out/>
  <testcase classname="rerun_failed_testCases.Code" name="enterValidCredentials" time="10.173">
    <failure message="just failing it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: just failing it
at org.testng.Assert.fail(Assert.java:99)
at rerun_failed_testCases.Code.enterValidCredentials(Code.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- enterValidCredentials -->
  <system-out/>
  <testcase classname="rerun_failed_testCases.Code" name="enterValidCredentials" time="10.214">
    <skipped/>
  </testcase> <!-- enterValidCredentials -->
  <system-out/>
  <testcase classname="rerun_failed_testCases.Code" name="enterValidCredentials" time="9.724">
    <skipped/>
  </testcase> <!-- enterValidCredentials -->
  <system-out/>
  <testcase classname="rerun_failed_testCases.Code" name="enterValidCredentials" time="12.271">
    <skipped/>
  </testcase> <!-- enterValidCredentials -->
  <system-out/>
</testsuite> <!-- rerun_failed_testCases.Code -->
